### ISSUE TITLE
Client side code

### ISSUE THREAD

**Issue by meganvanwelie** [olumidesan/scrabble#4]
Hey,
Your app is really great! I'm interested in adding re-draw capabilities, but it looks like the you've only hosted a build of the client side code. Is that right? Was that intentional, or could you host the client code so I could potentially make changes?
Thanks!

**Comment by olumidesan** [comment]
Hi, Megan.
Thanks for the compliment. It warms the heart.
Also, the client code is in the `dev` branch. you can `check` `it` `out` and make your proposed changes. I created a separate branch for development, `dev` and left `master` for the actual "production" code. 

Also, can you explain what you mean by 're-draw' capabilities?

**Comment by meganvanwelie** [comment]
Ah makes sense, I see it now, thanks! By re-draw I meant the ability for someone to turn their tiles back in in exchange for new ones. I believe you have it listed as the first item in the "known bugs". Is this something you are already working on?

**Comment by olumidesan** [comment]
Ah, wonderful! Thank you!
No, I'm currently not working on it. I'm working on the third known bug, the one with the mysterious disappearance of the rack pieces.

**Comment by meganvanwelie** [comment]
Great I will try and take a shot it then :) I was thinking of just adding a button into the existing set (maybe next to skip turn). Does that sound reasonable to you?

**Comment by olumidesan** [comment]
Of course! You'll see in the code that there's already a button there, just commented out, as I hadn't done the implementation of the actual piece-swapping: https://github.com/olumidesan/scrabble/blob/c563818d6f807a73cad223d6a797ce629a8c2289/client/src/containers/Rack/Rack.jsx#L852.

Please, feel free to make any changes you want.

**Comment by olumidesan** [comment]
This has been implemented in v2.4
